### ISSUE TITLE
Desktop launcher does nothing

### ISSUE THREAD

**Issue by dreua** [flathub/org.gnome.design.AppIconPreview#3]
The desktop launcher doesn't work for me, running from command line without problems. First glance at journalctl didn't show much but I can probably investigate further. Is this working for other users / environments?

Fedora 32 with Gnome.

**Comment by bilelmoussaoui** [comment]
It does work fine without any issues here

**Comment by dreua** [comment]
Can't reproduce after a reboot (i.e. it works as expected now).
